### ISSUE TITLE
ipfs.id is not a function

### ISSUE THREAD

**Issue by Powersource** [ipfs/js-ipfsd-ctl#161]
There isn't much info on `ipfsd.local` but [from this example](https://github.com/ipfs/js-ipfsd-ctl/blob/master/examples/local.js) it seemed like this should work.

```
const ipfsd = require('ipfsd-ctl')

ipfsd.local((err, ipfs) => {
    if (err) { throw err }

    ipfs.id(function (err, id) {
        if (err) { throw err }
        console.log(id);
    });
});
```

Error:

```
Uncaught TypeError: ipfs.id is not a function
    at ipfsd.local (file:///home/me/prj/web/viddist/index.js:8:10)
    at process.nextTick (/home/me/prj/web/viddist/node_modules/ipfsd-ctl/src/index.js:57:7)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

Had the same result with and without `IPFS_EXEC` set. Also tried having a regular go-ipfs node running and not.

```
{"diskinfo":{"free_space":108446048256,"fstype":"61267","total_space":95631613952},"environment":{"GOPATH":"/home/me/prj/go","IPFS_PATH":""},"ipfs_commit":"c5d362e3f","ipfs_version":"0.4.11-dev","memory":{"swap":0,"virt":227436000},"net":{"interface_addresses":["/ip4/127.0.0.1","/ip4/10.2.202.244","/ip6/::1","/ip6/fe80::80ca:2835:20da:f537"],"online":false},"runtime":{"arch":"amd64","compiler":"gc","gomaxprocs":4,"numcpu":4,"numgoroutines":6,"os":"linux","version":"go1.8.3"}}
```

**Comment by diasdavid** [comment]
@Powersource that `ipfs` instance is not an `ipfs-api` instance. Log its methods, it is something that is created here that exposes some commands but not all. You want to do a disposableAPI or create a js-ipfs-api instance that connects to that daemon started.

**Comment by Powersource** [comment]
Ok thanks, looked into the code a bit more and I think this should work (followed by using the Addr's to
connect using js-ipfs-api):

```
const ipfsd = require('ipfsd-ctl')

ipfsd.local((err, ipfs) => {
    if (err) { throw err }

    console.log(ipfs.apiAddr)
    console.log(ipfs.gatewayAddr)
});
```
Both of those log null. And I don't really understand the comment in the example linked above `// opens an api connection to local running ipfs node`.

**Comment by diasdavid** [comment]
Fixed with https://github.com/ipfs/js-ipfsd-ctl/pull/165 :)

**Comment by Powersource** [comment]
Trying this with 0.23 it still doesn't seem to work. [My code.](https://github.com/viddist/viddist/blob/c435887de884407597b697d222cf5eb27459ede3/index.js)

` {"diskinfo":{"free_space":104992063488,"fstype":"61267","total_space":92177629184},"environment":{"GOPATH":"/home/me/prj/go","IPFS_PATH":""},"ipfs_commit":"f55a7a03b","ipfs_version":"0.4.11-dev","memory":{"swap":0,"virt":219328000},"net":{"interface_addresses":["/ip4/127.0.0.1","/ip4/10.2.253.37","/ip6/::1","/ip6/fe80::80ca:2835:20da:f537"],"online":false},"runtime":{"arch":"amd64","compiler":"gc","gomaxprocs":4,"numcpu":4,"numgoroutines":5,"os":"linux","version":"go1.9"}}
`
